import { useState } from "react";
import { Alert, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import { useOrganization } from "../../app/OrganizationContext";
import { DataTable } from "../../components/DataTable";
import { useCashBook } from "./useCashBook";
import type { CashTransaction } from "../../types/cashbook";

const today = new Date().toISOString().slice(0, 10);

export function CashBookPage() {
  const { companyId, branchId } = useOrganization();
  const book = useCashBook(companyId || undefined, branchId || undefined);
  const [tab, setTab] = useState(0); const [details, setDetails] = useState<CashTransaction | null>(null);
  const [transactionOpen, setTransactionOpen] = useState(false); const [accountOpen, setAccountOpen] = useState(false);
  const [form, setForm] = useState({ cash_account_id: "", target_cash_account_id: "", financial_year_id: "", transaction_type: "receipt" as "receipt" | "payment" | "transfer", transaction_date: today, amount: "", reference: "", description: "" });
  const [accountForm, setAccountForm] = useState({ account_code: "", name: "", currency: "USD", opening_balance: "0.00" });
  const accounts = book.accounts.data ?? []; const transactions = book.transactions.data ?? [];
  const update = (key: keyof typeof form, value: string) => setForm((old) => ({ ...old, [key]: value }));
  const submit = async () => { await book.create.mutateAsync({ ...form, company_id: companyId, branch_id: branchId || null, target_cash_account_id: form.transaction_type === "transfer" ? form.target_cash_account_id : null, financial_year_id: form.financial_year_id }); setTransactionOpen(false); };
  if (!companyId) return <Alert severity="info">Select a company to use the Cash Book.</Alert>;
  return <Stack spacing={3}>
    <Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={2}><div><Typography variant="h4">Cash Book</Typography><Typography color="text.secondary">Record, approve and audit receipts, payments and transfers.</Typography></div><Stack direction="row" gap={1}><Button variant="outlined" onClick={() => setAccountOpen(true)}>New account</Button><Button variant="contained" onClick={() => setTransactionOpen(true)} disabled={!accounts.length}>New transaction</Button></Stack></Stack>
    <Stack direction={{ xs: "column", md: "row" }} spacing={2}>{accounts.map((account) => <Card key={account.id} sx={{ flex: 1 }}><CardContent><Typography color="text.secondary" variant="body2">{account.name}</Typography><Typography variant="h5">{account.currency} {Number(account.balance).toFixed(2)}</Typography><Typography variant="caption">{account.account_code}</Typography></CardContent></Card>)}</Stack>
    <Card><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable"><Tab label="Transactions" /><Tab label="Daily summary" /><Tab label="Approval queue" /></Tabs><CardContent>
      {tab === 1 ? <DataTable columns={["Account", "Date", "Receipts", "Payments", "Transfers", "Closing"]} rows={(book.summary.data ?? []).map((row) => [row.cash_account_name, row.summary_date, row.receipts, row.payments, `${row.transfers_in} / ${row.transfers_out}`, row.closing_balance])} /> :
      <DataTable columns={["Document", "Date", "Type", "Amount", "State", "Actions"]} rows={transactions.filter((item) => tab !== 2 || ["SUBMITTED", "APPROVED"].includes(item.state)).map((item) => [item.document_number ?? "—", item.transaction_date, item.transaction_type, item.amount, item.state,
        <Stack direction="row" key={item.id}><Button size="small" onClick={() => setDetails(item)}>Details</Button>{item.state === "DRAFT" && <Button size="small" onClick={() => book.transition.mutate({ id: item.id, action: "submit" })}>Submit</Button>}{item.state === "SUBMITTED" && <Button size="small" onClick={() => book.transition.mutate({ id: item.id, action: "approve" })}>Approve</Button>}{item.state === "APPROVED" && <Button size="small" onClick={() => book.transition.mutate({ id: item.id, action: "post" })}>Post</Button>}{item.state === "POSTED" && <Button size="small" color="warning" onClick={() => book.transition.mutate({ id: item.id, action: "reverse" })}>Reverse</Button>}</Stack>])} />}</CardContent></Card>
    <Dialog open={transactionOpen} onClose={() => setTransactionOpen(false)} fullWidth maxWidth="sm"><DialogTitle>New cash transaction</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField select label="Type" value={form.transaction_type} onChange={(e) => update("transaction_type", e.target.value)}><MenuItem value="receipt">Receipt</MenuItem><MenuItem value="payment">Payment</MenuItem><MenuItem value="transfer">Transfer</MenuItem></TextField><TextField select label="Cash account" value={form.cash_account_id} onChange={(e) => update("cash_account_id", e.target.value)}>{accounts.map((account) => <MenuItem key={account.id} value={account.id}>{account.account_code} — {account.name}</MenuItem>)}</TextField>{form.transaction_type === "transfer" && <TextField select label="Target account" value={form.target_cash_account_id} onChange={(e) => update("target_cash_account_id", e.target.value)}>{accounts.filter((account) => account.id !== form.cash_account_id).map((account) => <MenuItem key={account.id} value={account.id}>{account.name}</MenuItem>)}</TextField>}<TextField label="Financial year ID" value={form.financial_year_id} onChange={(e) => update("financial_year_id", e.target.value)} required /><TextField type="date" label="Date" InputLabelProps={{ shrink: true }} value={form.transaction_date} onChange={(e) => update("transaction_date", e.target.value)} /><TextField type="number" label="Amount" value={form.amount} onChange={(e) => update("amount", e.target.value)} /><TextField label="Reference" value={form.reference} onChange={(e) => update("reference", e.target.value)} /><TextField label="Description" multiline minRows={2} value={form.description} onChange={(e) => update("description", e.target.value)} /></Stack></DialogContent><DialogActions><Button onClick={() => setTransactionOpen(false)}>Cancel</Button><Button variant="contained" onClick={submit} disabled={!form.cash_account_id || !form.financial_year_id || !form.amount || book.create.isPending}>Save draft</Button></DialogActions></Dialog>
    <Dialog open={accountOpen} onClose={() => setAccountOpen(false)} fullWidth maxWidth="sm"><DialogTitle>New cash account</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField label="Code" value={accountForm.account_code} onChange={(e) => setAccountForm({ ...accountForm, account_code: e.target.value.toUpperCase() })} /><TextField label="Name" value={accountForm.name} onChange={(e) => setAccountForm({ ...accountForm, name: e.target.value })} /><TextField label="Currency" value={accountForm.currency} onChange={(e) => setAccountForm({ ...accountForm, currency: e.target.value.toUpperCase() })} /><TextField type="number" label="Opening balance" value={accountForm.opening_balance} onChange={(e) => setAccountForm({ ...accountForm, opening_balance: e.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setAccountOpen(false)}>Cancel</Button><Button variant="contained" onClick={async () => { await book.createAccount.mutateAsync({ ...accountForm, company_id: companyId, branch_id: branchId || null }); setAccountOpen(false); }}>Create</Button></DialogActions></Dialog>
    <Dialog open={Boolean(details)} onClose={() => setDetails(null)} fullWidth maxWidth="sm"><DialogTitle>{details?.document_number}</DialogTitle><DialogContent><Stack spacing={1}><Typography>Type: {details?.transaction_type}</Typography><Typography>Amount: {details?.amount}</Typography><Typography>Date: {details?.transaction_date}</Typography><Typography>State: {details?.state}</Typography><Typography>Reference: {details?.reference || "—"}</Typography><Typography>Description: {details?.description || "—"}</Typography>{details?.reversal_of_id && <Typography>Reversal of: {details.reversal_of_id}</Typography>}</Stack></DialogContent><DialogActions><Button onClick={() => setDetails(null)}>Close</Button></DialogActions></Dialog>
  </Stack>;
}
