import { useState } from "react";
import { Alert, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import { useOrganization } from "../../app/OrganizationContext";
import { DataTable } from "../../components/DataTable";
import { useExpenses } from "./useExpenses";
import type { Expense } from "../../types/expenses";

const today = new Date().toISOString().slice(0, 10);

export function ExpensePage() {
  const { companyId, branchId } = useOrganization();
  const [filterStatus, setFilterStatus] = useState(""); const [search, setSearch] = useState("");
  const expenses = useExpenses(companyId || undefined, branchId || undefined, filterStatus || undefined, search || undefined);
  const [tab, setTab] = useState(0); const [entryOpen, setEntryOpen] = useState(false); const [categoryOpen, setCategoryOpen] = useState(false); const [details, setDetails] = useState<Expense | null>(null);
  const [form, setForm] = useState({ financial_year_id: "", date: today, category_id: "", account_id: "", amount: "", tax_amount: "0.00", payment_method: "cash", cash_account_id: "", vendor: "", description: "", reference: "" });
  const [category, setCategory] = useState({ code: "", name: "", description: "" });
  const rows = expenses.expenses.data ?? []; const categories = expenses.categories.data ?? [];
  const update = (key: keyof typeof form, value: string) => setForm((old) => ({ ...old, [key]: value }));
  if (!companyId) return <Alert severity="info">Select a company to use Expenses.</Alert>;
  const save = async () => { await expenses.create.mutateAsync({ ...form, company_id: companyId, branch_id: branchId || null, cash_account_id: form.cash_account_id || null }); setEntryOpen(false); };
  const filtered = tab === 1 ? rows.filter((row) => ["SUBMITTED", "APPROVED"].includes(row.status)) : rows;
  return <Stack spacing={3}>
    <Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={2}><div><Typography variant="h4">Expenses</Typography><Typography color="text.secondary">Capture, approve and post company expenses with an audit trail.</Typography></div><Stack direction="row" gap={1}><Button variant="outlined" onClick={() => setCategoryOpen(true)}>Categories</Button><Button variant="contained" onClick={() => setEntryOpen(true)}>New expense</Button></Stack></Stack>
    <Stack direction={{ xs: "column", sm: "row" }} spacing={2}><Card sx={{ flex: 1 }}><CardContent><Typography color="text.secondary">Total shown</Typography><Typography variant="h5">{rows.reduce((sum, row) => sum + Number(row.amount) + Number(row.tax_amount), 0).toFixed(2)}</Typography></CardContent></Card><Card sx={{ flex: 1 }}><CardContent><Typography color="text.secondary">Approval queue</Typography><Typography variant="h5">{rows.filter((row) => row.status === "SUBMITTED").length}</Typography></CardContent></Card><Card sx={{ flex: 1 }}><CardContent><Typography color="text.secondary">Posted</Typography><Typography variant="h5">{rows.filter((row) => row.status === "POSTED").length}</Typography></CardContent></Card></Stack>
    <Card><Tabs value={tab} onChange={(_, value) => setTab(value)}><Tab label="All expenses" /><Tab label="Approval queue" /><Tab label="Categories" /></Tabs><CardContent>{tab === 2 ? <DataTable columns={["Code", "Category", "Description", "Status"]} rows={categories.map((item) => [item.code, item.name, item.description || "—", item.is_active ? "Active" : "Inactive"])} /> : <><Stack direction={{ xs: "column", sm: "row" }} spacing={2} sx={{ mb: 2 }}><TextField size="small" label="Search number, vendor or description" value={search} onChange={(e) => setSearch(e.target.value)} /><TextField select size="small" label="Status" value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)} sx={{ minWidth: 160 }}><MenuItem value="">All</MenuItem>{["DRAFT", "SUBMITTED", "APPROVED", "POSTED", "REJECTED", "CANCELLED"].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField></Stack><DataTable columns={["Number", "Date", "Vendor", "Amount", "Status", "Actions"]} rows={filtered.map((item) => [item.expense_number, item.date, item.vendor || "—", (Number(item.amount) + Number(item.tax_amount)).toFixed(2), <Chip size="small" label={item.status} color={item.status === "POSTED" ? "success" : item.status === "REJECTED" ? "error" : "default"} />, <Stack direction="row" key={item.id}><Button size="small" onClick={() => setDetails(item)}>Details</Button>{item.status === "DRAFT" && <Button size="small" onClick={() => expenses.transition.mutate({ id: item.id, action: "submit" })}>Submit</Button>}{item.status === "SUBMITTED" && <Button size="small" onClick={() => expenses.transition.mutate({ id: item.id, action: "approve" })}>Approve</Button>}{item.status === "APPROVED" && <Button size="small" onClick={() => expenses.transition.mutate({ id: item.id, action: "post" })}>Post</Button>}{item.status === "POSTED" && <Button size="small" color="warning" onClick={() => expenses.transition.mutate({ id: item.id, action: "reverse" })}>Reverse</Button>}</Stack>])} /></>}</CardContent></Card>
    <Dialog open={entryOpen} onClose={() => setEntryOpen(false)} fullWidth maxWidth="sm"><DialogTitle>New expense</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}>{(["financial_year_id", "account_id"] as const).map((key) => <TextField key={key} label={key === "financial_year_id" ? "Financial year ID" : "Expense account ID"} value={form[key]} onChange={(e) => update(key, e.target.value)} required />)}<TextField select label="Category" value={form.category_id} onChange={(e) => update("category_id", e.target.value)}>{categories.map((item) => <MenuItem key={item.id} value={item.id}>{item.code} — {item.name}</MenuItem>)}</TextField><TextField type="date" label="Date" InputLabelProps={{ shrink: true }} value={form.date} onChange={(e) => update("date", e.target.value)} /><TextField type="number" label="Amount" value={form.amount} onChange={(e) => update("amount", e.target.value)} /><TextField type="number" label="Tax amount" value={form.tax_amount} onChange={(e) => update("tax_amount", e.target.value)} /><TextField select label="Payment method" value={form.payment_method} onChange={(e) => update("payment_method", e.target.value)}>{["cash", "bank", "card", "credit", "other"].map((value) => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField label="Cash account ID (for cash/bank/card)" value={form.cash_account_id} onChange={(e) => update("cash_account_id", e.target.value)} /><TextField label="Vendor" value={form.vendor} onChange={(e) => update("vendor", e.target.value)} /><TextField label="Description" multiline minRows={2} value={form.description} onChange={(e) => update("description", e.target.value)} /><TextField label="Reference" value={form.reference} onChange={(e) => update("reference", e.target.value)} /></Stack></DialogContent><DialogActions><Button onClick={() => setEntryOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={!form.financial_year_id || !form.category_id || !form.account_id || !form.amount || expenses.create.isPending}>Save draft</Button></DialogActions></Dialog>
    <Dialog open={categoryOpen} onClose={() => setCategoryOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Expense category</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField label="Code" value={category.code} onChange={(e) => setCategory({ ...category, code: e.target.value })} /><TextField label="Name" value={category.name} onChange={(e) => setCategory({ ...category, name: e.target.value })} /><TextField label="Description" value={category.description} onChange={(e) => setCategory({ ...category, description: e.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setCategoryOpen(false)}>Close</Button><Button variant="contained" onClick={async () => { await expenses.createCategory.mutateAsync({ ...category, company_id: companyId, branch_id: branchId || null }); setCategoryOpen(false); }}>Create</Button></DialogActions></Dialog>
    <Dialog open={Boolean(details)} onClose={() => setDetails(null)} fullWidth maxWidth="sm"><DialogTitle>{details?.expense_number}</DialogTitle><DialogContent><Stack spacing={1}><Typography>Date: {details?.date}</Typography><Typography>Amount: {details && (Number(details.amount) + Number(details.tax_amount)).toFixed(2)}</Typography><Typography>Status: {details?.status}</Typography><Typography>Vendor: {details?.vendor || "—"}</Typography><Typography>Description: {details?.description || "—"}</Typography><Typography>Attachment metadata: {details?.attachment ? JSON.stringify(details.attachment) : "None"}</Typography></Stack></DialogContent><DialogActions><Button onClick={() => setDetails(null)}>Close</Button></DialogActions></Dialog>
  </Stack>;
}
